server:
  port: 80
  servlet:
    context-path: /security

spring:
  datasource:
    url: jdbc:mysql://localhost:3306/security?useUnicode=true&characterEncoding=utf8&useSSL=false
    username: root
    password: root
    hikari:
      auto-commit: true
      maximum-pool-size: 10
  jpa:
    show-sql: true
    open-in-view: true
    database-platform: org.hibernate.dialect.MySQL5InnoDBDialect
  http:
    encoding:
      charset: UTF-8